plugins {
    id 'java'
    id 'org.springframework.boot' version '4.0.6'
    id 'io.spring.dependency-management' version '1.1.7'
}

apply from: 'version.gradle'

group = 'org'
version = loadVersion().getVersion()
description = 'crochet'

java {
  toolchain {
    languageVersion = JavaLanguageVersion.of(26)
  }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    maven { url 'https://repo.spring.io/milestone' }
    mavenCentral()
}

ext {
    set('springCloudVersion', "2025.1.1")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-aspectj'
    implementation "org.springframework.boot:spring-boot-starter-cache"
    implementation 'org.springframework.cloud:spring-cloud-starter-circuitbreaker-resilience4j'
    implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-client'
    implementation 'com.github.ben-manes.caffeine:caffeine:3.1.8'

    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.2'

    implementation 'jakarta.validation:jakarta.validation-api:3.1.0'

    implementation 'com.mysql:mysql-connector-j:8.4.0'
    implementation 'org.liquibase:liquibase-core:4.30.0'
    implementation 'com.h2database:h2:2.2.224'
    implementation 'org.postgresql:postgresql:42.7.7'

    compileOnly 'org.projectlombok:lombok:1.18.46'
    annotationProcessor 'org.projectlombok:lombok:1.18.46'

    implementation 'org.mapstruct:mapstruct:1.6.3'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'

    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'

    implementation 'com.google.firebase:firebase-admin:9.4.1'

    implementation 'io.hypersistence:hypersistence-utils-hibernate-73:3.15.2'

    // https://mvnrepository.com/artifact/com.turkraft.springfilter/jpa
    implementation 'com.turkraft.springfilter:jpa:3.1.9'

    // PayPal Server SDK
    implementation 'com.paypal.sdk:paypal-server-sdk:2.2.0'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.security:spring-security-test:6.3.0'
    testImplementation 'org.mockito:mockito-core:5.11.0'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.12.0'

    testCompileOnly 'org.projectlombok:lombok:1.18.46'
    testAnnotationProcessor 'org.projectlombok:lombok:1.18.46'
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}

jar {
    enabled = false
}

test {
    useJUnitPlatform()
}