services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.slim
      secrets:
        - secrets
    image: tieuphuongcrochet:latest
    ports:
      - "8080:8080"
    env_file:
      - .env.dev

secrets:
  secrets:
    file: ./secrets.txt
