# Custom jre build
FROM eclipse-temurin:21-jdk-alpine AS build

WORKDIR /workspace/app

# Copy only the files needed for the build
COPY gradlew .
COPY gradle gradle
COPY version.properties .
COPY version.gradle .
COPY build.gradle .
COPY settings.gradle .
COPY src src

# Build the application
RUN --mount=type=cache,target=/root/.gradle \
    --mount=type=secret,id=secrets,required \
    sed -i 's/\r//' gradlew \
    && chmod +x gradlew \
    && ./gradlew bootJar --no-daemon -x test

# Extract the application dependencies
RUN mkdir -p build/extracted \
    && (cd build/extracted && jar xf ../libs/*.jar)

# Analyze the dependencies contained in the fat jar
RUN jdeps --ignore-missing-deps -q \
    --recursive \
    --multi-release 21 \
    --print-module-deps \
    --class-path 'build/extracted/BOOT-INF/lib/*' \
    build/libs/*.jar > deps.info

# Create the custom JRE
RUN jlink \
    --verbose \
    --add-modules $(cat deps.info) \
    --compress 2 \
    --no-header-files \
    --no-man-pages \
    --output /custom_jre

# Use the custom jre as a base image
FROM debian:bookworm-slim
ENV JAVA_HOME=/opt/java/openjdk
ENV PATH "${JAVA_HOME}/bin:${PATH}"
COPY --from=build /custom_jre $JAVA_HOME

WORKDIR /app
VOLUME /tmp

# Copy application files
COPY --from=build /workspace/app/build/extracted/BOOT-INF/lib /app/lib
COPY --from=build /workspace/app/build/extracted/META-INF /app/META-INF
COPY --from=build /workspace/app/build/extracted/BOOT-INF/classes /app

EXPOSE 8080
ENTRYPOINT ["java", \
    "-XX:+UseContainerSupport", \
    "-XX:MaxRAMPercentage=75.0", \
    "-cp", ".:/app/lib/*", \
    "org.crochet.CrochetApplication"]
