spring:
  config:
    activate:
      on-profile: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        # Cấu hình dev hiện tại
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        jdbc:
          batch_size: 50  # Tăng từ 25 lên 50
          batch_versioned_data: true
          batch_builder: legacy
        order_inserts: true
        order_updates: true
        
        # Thêm cấu hình optimization
        connection:
          provider_disables_autocommit: false
        query:
          fail_on_pagination_over_collection_fetch: false
          in_clause_parameter_padding: true
          plan_cache_max_size: 2048
          plan_parameter_metadata_max_size: 128
          timeout: 30
        batch_fetch_style: DYNAMIC
        default_batch_fetch_size: 16
        enable_lazy_load_no_trans: false
        statistics:
          enabled: true
          log_slow_query: true
          slow_query_threshold: 1000
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Thêm cấu hình datasource optimization
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1

  liquibase:
    enabled: false
    # Thêm cấu hình để suppress warning
    parameters:
      logLevel: INFO
      showSummary: true
      showSummaryOutput: true

logging:
  level:
    org:
      liquibase: INFO  # Thay đổi từ debug xuống INFO
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace
        stat: debug
      springframework:
        cache: debug
    root: info
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"