spring:
  config:
    activate:
      on-profile: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql-crochet-yarn-magneticoak-ce4a.k.aivencloud.com:22456/defaultdb?ssl-mode=REQUIRED
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: false
  data:
    redis:
      host: crochet-cache-phanvanluom97cv-60b9.g.aivencloud.com
      port: 27138
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USER}
logging:
  level:
    org:
      hibernate:
        SQL: debug